# Generated by Django 4.2 on 2023-08-03 15:14

from django.db import migrations, models
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_name', models.CharField(blank=True, help_text='Enter Company Name which is written into Registration Form', max_length=50, verbose_name='Registered Company Name')),
                ('email', models.EmailField(blank=True, help_text='Enter Company Email', max_length=50)),
                ('description', models.TextField(blank=True, help_text="Enter about Company's Goals , Aim and Contribution or Ideas", verbose_name='Company Description')),
                ('website', models.URLField(blank=True, help_text="Enter Company's official Website", max_length=60, null=True, verbose_name='Company website')),
                ('Contact_Number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, help_text="Enter Candidate's Email", max_length=50)),
                ('contact', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('add1', models.CharField(blank=True, max_length=60)),
                ('query', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recruitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('work', models.CharField(blank=True, help_text='choose working mode', max_length=20, verbose_name='working status')),
                ('Last_update', models.DateTimeField(auto_now=True, help_text='Last update in This Form')),
                ('recruit', models.CharField(blank=True, help_text='Which Kind of Candidate requirement (Fresher , Experience )', max_length=20)),
                ('vacancy', models.IntegerField(default=0)),
                ('demanded_skill', models.CharField(blank=True, help_text='Enter Demanded Skill', max_length=50)),
                ('status', models.CharField(blank=True, help_text='Want Full Time or Part Time', max_length=50, verbose_name='Required')),
                ('contact', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('salary_scale', models.CharField(blank=True, max_length=40)),
                ('job_description', models.TextField(blank=True, help_text='what kind of candidate you are Wanting', verbose_name='job description')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(blank=True, max_length=60)),
                ('Key_Skills', models.CharField(blank=True, help_text='Enter Your Skills ', max_length=60)),
                ('Contact_Number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('Alternative_Number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('portfolio', models.URLField(blank=True, help_text="Enter Candidate's Portfolio URL", max_length=60, null=True, verbose_name='Portfolio')),
                ('college_name', models.CharField(blank=True, help_text='Enter College Name ', max_length=100, verbose_name='College Name')),
                ('birth_date', models.DateField(blank=True, default=django.utils.timezone.now, help_text='Enter Date of Birth', verbose_name='Date Of Birth')),
                ('cgp', models.DecimalField(blank=True, decimal_places=2, help_text='Enter CGP or Percentage of Last Year', max_digits=5, verbose_name='CGP Or Percentage')),
                ('email', models.EmailField(blank=True, help_text="Enter Candidate's Email", max_length=50)),
                ('file', models.FileField(blank=True, help_text='Upload Your Resume with demanded skills by company', upload_to='app1/static/candidate', verbose_name='Upload Resume')),
                ('description', models.TextField(blank=True, help_text='Why should you hire ', verbose_name='Cover Page')),
                ('choice', models.CharField(blank=True, help_text='Are You Graduate or Under Graduate', max_length=20)),
            ],
        ),
    ]
